name: "Sand and Blood"
baseUrl: http://sand-and-blood.fedran.com
markdown: redcarpet
pygments: false

# Look and feel of elements not controlled by CSS.
windowsTile: "red"

# Atom Feed
atomCopyright: "2014, D. Moonfire; Some Rights Reserved."

# Table of Contents and collections. If this isn't missed, the TOC by default will put "by" and the name of the author.
author: "D. Moonfire"

# Blog posts
permalink: /news/:year/:month/:day-:title
