name: "Site Name"
baseUrl: http://url-of-site.com

# Look and feel of elements not controlled by CSS.
brand: "Fancy Title"
windowsTile: "red"

# Atom Feed
atomCopyright: "2013-2014, Bob; Some Rights Reserved."

# Comments
disqus:
  enabled: false
  name: "short-name-of-discus-site"
  baseurl: "http://url-of-discus-site.com/"

piwik:
  enabled: true
  id: 1
  server: name.server.com

# Table of Contents and collections. If this isn't missed, the TOC by default will put "by" and the name of the author.
author: "Bob"

# Blog posts
permalink: /news/:year/:month/:day-:title
